# This is a basic workflow to help you get started with Actions

name: message-logging
on:
  push:
    branches: [ "main" ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: workflow commands logging messages
        run: |
          echo "::debug::This is a debug message"
          echo "This is an info message"
          echo "::error::This is an error message"
          echo "::warning::This is a warning message"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
